name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 配置 Golang 环境
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"

      # 检出代码
      - name: Checkout Trigger Branch
        uses: actions/checkout@v4

      # 执行单元测试
      - name: Execute Unit Test
        run: ./test.sh
